
* সাম্প্রতিক তথ্য

 1) মোহাম্মদ বিন নায়েফকে ক্রাউন প্রিন্সের পদ থেকে সরিয়ে নিজে ক্ষমতা নেন
     মোহাম্মদ বিন সালমান ।
 2) ১৯৬০ সালে ওপেক এবং ২০১৬ সালে ওপেক প্লাস গঠিত হয় ।
 3) ওপেক প্লাসের সদস্য সংখ্যা ২৩ ।(ডাউট আছে) 
 4) ইসরায়েলের প্রতিরক্ষামন্ত্রী বেনি গ্যান্টজ ।
 5) পাকিস্তানের অর্থমন্ত্রী ইসহাক দার  ।
 6) সর্বশেষ বাংলাদেশে  আঘাত হানা ঘূর্ণিঝড় হল  সিত্রাং ।
 7) মধ্যপ্রাচ্যে যুক্তরাষ্ট্রের সবচেয়ে বড় বিমানঘাঁটি এই কাতারেই।
 8) কাতার দেশটিতে সামরিক ঘাঁটি আছে তুরস্কেরও।
 9) ১৯৯৬ সালে বিশ্বমানের সংবাদমাধ্যম হিসেবে কাতারে শুরু হয় আল-জাজিরার পথচলা।
 10) *২০১৭ সালের ৫ জুন* সৌদি ও তার আরব মিত্ররা কাতারের ওপর সর্বাত্মক অবরোধ আরোপ করে।
 11) ২০১৭ সালে মিত্রদের নিয়ে কাতারের ওপর সর্বাত্মক অবরোধ আরোপ করে সৌদি। অবরোধ
      তুলে নিতে দেওয়া *১৩টি শর্তের অন্যতম ছিল আল-জাজিরা বন্ধ করে দেওয়া।*
 12) *২০২১ সালের জানুয়ারিতে* অবরোধ তুলে নেয় সৌদি জোট।
 13) দেশের একমাত্র নারী জেলা পরিষদ চেয়ারম্যান *সালমা রহমান পিরোজপুর* জেলা পরিষদের
      চেয়ারম্যান
 14) পাকিস্তানের প্রেসিডেন্ট *আরিফ আলভি*
 15) পাঞ্জাবের *ওয়াজিরাবাদ শহরের আল্লাহওয়ালা চক এলাকার* কাছে ইমরান খানের ওপর এ হামলা হয়
 16) কুইক রেন্টালের জন্য বিদ্যুৎ ও জ্বালানির দ্রুত সরবরাহ বৃদ্ধি (বিশেষ বিধান) আইন ২০১০ করা
      হয় ।
 17) দেশের দ্বিতীয় স্যাটেলাইট ‘বঙ্গবন্ধু স্যাটেলাইট-২’-এর ধরন নির্ধারণের জন্য ফ্রান্সের
      প্রাইসওয়াটারহাউসকুপার্সকে (পিডব্লিউসি) নিয়োগ দিয়েছে বিএসসিএল।
 18) ২০১৮ সালের ১২ মে বঙ্গবন্ধু স্যাটেলাইট-১ মহাকাশে উৎক্ষেপণের মাধ্যমে বিশ্বের ৫৭তম দেশ
      হিসেবে স্যাটেলাইটের অভিজাত ক্লাবে প্রবেশ করে বাংলাদেশ।এতে বাংলাদেশের খরচ হয় ২ হাজার
       ৯০২ কোটি টাকা।
 19) বঙ্গবন্ধু স্যাটেলাইট-২ হাইব্রিড স্যাটেলাইট হতে পারে।
 20) *বঙ্গবন্ধু স্যাটেলাইট-১  থেকে বছরে ১২০ কোটি* পাচ্ছি।
 21) মহাকাশ বিষয়ক রাশিয়ার রাষ্ট্রীয় প্রতিষ্ঠান *গ্লাভকসমসের* সঙ্গে বঙ্গবন্ধু স্যাটেলাইট-২
      তৈরি ও উৎক্ষেপণ বিষয়ে সহযোগিতা স্মারক স্বাক্ষরের মধ্য দিয়ে আর্থ অবজারভেটরি
      ক্যাটাগরির এই  স্যটেলাইটটির নির্মাণের অভিযাত্রা শুরু হয়।
 22) *২০২১ সালের ১২ ডিসেম্বর* বাংলাদেশ ফাইভ-জি যুগে প্রবেশ করেছে।
 23) ইরানের পররাষ্ট্রমন্ত্রী হোসেইন আমির আবদুল্লাহিয়ান
 24) চীন, ভারত, তুরস্ক ও শ্রীলঙ্কার মতো দেশগুলো মস্কোর কাছ থেকে তেল কিনছে।
 25) যুক্তরাষ্ট্র ২৪ জানুয়ারি থেকে ৩ অক্টোবর পর্যন্ত *ইউক্রেনকে ৫২০০ কোটি ডলারের* সামরিক,
     মানবিক ও অন্যান্য খাতের সহায়তা দিয়েছে।
 26) *The non-OPEC countries which export crude oil are termed as OPEC plus
     countries.* OPEC plus countries include *Azerbaijan, Bahrain, Brunei,
     Kazakhstan, Malaysia, Mexico, Oman, Russia, South Sudan and Sudan*.
 27) cop-27 অনুষ্ঠিত হয় ৬ থেকে ১৮ নভেম্বর মিশরের শার্ম আল শেখে । এর স্লোগান
     Together For Implementation.অংশগ্রহণ কারী *দেশ ১৯৮ টি ।*
 28) বাংলাদেশ আন্তর্জাতিক মেধাস্বত্ব সংস্থার (WIPO) *১১৬ তম দেশ হিসেবে মারাকেশ চুক্তি* অনুস্বাক্ষর করে।
 29) দেশের প্রথম ছয় লেনের দৃষ্টিনন্দন সেতু - *'মধুমতী সেতু'।*
 30) দেশের একমাত্র বিদ্যুৎ সঞ্চালন সংস্থা – *পাওয়ার গ্রিড কোম্পানি অব বাংলাদেশ লিঃ (PGCB)।*
 31) *১ অক্টোবর ২০২২ মৃত্যুবরণ করেন দৈনিক বাংলার সম্পাদক তোয়াব খান।* মুক্তিযুদ্ধের সময় তিনি শব্দ
     সৈনিক হিসাবে ভূমিকা রেখেছিলেন তোয়াব খান। সেই সময় তিনি 'পিণ্ডির প্রলাপ' নামের একটি অনুষ্ঠান
      উপস্থাপনা করতেন।
 32) *৯৫তম একাডেমি অ্যাওয়ার্ডসের* বিদেশি ভাষার ছবি বিভাগের জন্য বাংলাদেশ থেকে মনোনীত হয়েছে
     *মেজবাউর রহমান সুমন পরিচালিত 'হাওয়া'।*
 33) প্রধানমন্ত্রী শেখ হাসিনার ৭৬তম জন্মবার্ষিকী উপলক্ষে প্রকাশ পেল প্রামাণ্যচিত্র *'শেখ হাসিনা:
     অ্যা ট্রু লিজেন্ড'।* প্রামাণ্যচিত্রটি পরিচালনা করেছেন *আয়শা এরিন।*
 34) *১৯৭১ সালে পাকিস্তানের সেনাবাহিনী কর্তৃক বাংলাদেশে চালানো গণহত্যাকে স্বীকৃতির* দাবিতে মার্কিন
      যুক্তরাষ্ট্রের পার্লামেন্টের নিম্নকক্ষ প্রতিনিধি পরিষদে (হাউস অব রিপ্রেজেন্টিভস) একটি প্রস্তাব আনা
      হয়েছে। *কংগ্রেসম্যান রো খান্না ও কংগ্রেসম্যান স্টিভ চ্যাট* এ প্রস্তাব তোলেন।
 35) দেশে রপ্তানির তালিকায় নতুন দুটি পণ্য যোগ হয়েছে। দুটিই প্লাস্টিকশিল্পের কাঁচামাল - *পেট রেজিন ও
     পিভিসি (পলিভিনাইল ক্লোরাইড)।* বাংলাদেশে এ দুটি পণ্য এত দিন ছিল শতভাগ আমদানিনির্ভর।
     দেশের রপ্তানি পণ্যের তালিকায় এত দিন ছিল ২৬৭টি পণ্য। এর বেশির ভাগই পোশাক খাতের।
     এ দুটি পণ্য যোগ হওয়ায় *সংখ্যা বেড়ে দাঁড়াল ২৬৯।*
 36) *ডিজিটাল নিরাপত্তা আইন, ২০১৮-এর ধারা ১৫* অনুযায়ী সরকারি *২৯টি প্রতিষ্ঠানকে গুরুত্বপূর্ণ তথ্য
     পরিকাঠামো হিসেবে ঘোষণা। করা হলো।*
 37) পঞ্চমবারের মতো *জাতিসংঘ মানবাধিকার কাউন্সিলের (ইউএনএইচআরসি) সদস্য নির্বাচিত হয়েছে
     বাংলাদেশ।* যুক্তরাষ্ট্রের নিউইয়র্কে জাতিসংঘ সাধারণ পরিষদ হলে এ-সংক্রান্ত ভোটাভুটি হয়। ভোটে
     জাতিসংঘের ১৯৩টি সদস্যদেশের মধ্যে ১৮৯টি ভোট দেয়। ভোটাভুটিতে এশিয়া ও প্রশান্ত মহাসাগরীয়
     অঞ্চলের দেশগুলোর মধ্যে *সর্বোচ্চ ১৬০টি ভোট* পেয়ে সদস্য নির্বাচিত হয় বাংলাদেশ।
 38) ভারতের রাজধানী দিল্লিতে শুরু হওয়া আন্তর্জাতিক সৌর জোটের (আইএসএ) পঞ্চম সমাবেশে এশিয়া
     প্যাসিফিক অঞ্চল থেকে বাংলাদেশ সহসভাপতি নির্বাচিত হয়েছে। এ জোটে সভাপতি নির্বাচিত হয়েছে ভারত ও
     সহসভাপতি নির্বাচিত হয়েছে ফ্রান্স।
 39) নিউইয়র্কে *ম্যাকডোনাল্ড অ্যাভিনিউর নতুন নাম লিটল বাংলাদেশ।* ১৬ অক্টোবর নিউইয়র্ক সিটির
     ব্রুকলিনে প্রবাসী বাংলাদেশি অধ্যুষিত ম্যাকডোনাল্ড অ্যাভিনিউর নতুন নামকরণ হয়েছে 'লিটল বাংলাদেশ।
 40) *নারী এশিয়া কাপে মালয়েশিয়ার* বিপক্ষে অভিষেক টি-২০ তে হ্যাটট্রিক করেন বাংলাদেশের
     *ফারিহা ইসলাম।*
 41) ত্রিপুরা ভাষায় (ককবরক) বঙ্গবন্ধু শেখ মুজিবুর রহমানের অসমাপ্ত আত্মজীবনী' অনুবাদ করেছেন
     কুমিল্লা বিশ্ববিদ্যালয়ের (কুবি) *নৃবিজ্ঞান বিভাগের সপ্তম ব্যাচের সাবেক শিক্ষার্থী যুবরাজ দেববর্মা।* তিনি
     *ককবরক'* বইটির নাম দিয়েছেন *'পাইথাকরা লাংমা';* এর অর্থ অসমাপ্ত আত্মজীবনী'।
 42) ২৪ অক্টোবর ২০২২ ঘূর্ণিঝড় সিত্রাং বাংলাদেশের উপকূলবর্তী বরিশাল, চট্টগ্রাম ও খুলনা বিভাগে
     আঘাত হানে। সিত্রাং' নামকরণ করে থাইল্যান্ড। ভিয়েতনামি ভাষায় যার অর্থ 'পাতা'।
 43) ILO এর বর্তমান ও ১১তম মহাপরিচালক Gilbert F. Houngbo (টোগো)। ১ অক্টোবর, ২০২২ সালে
     তিনি দায়িত্ব গ্রহণ করেন।
 44) ILO এর বর্তমান ও ১১তম মহাপরিচালক Gilbert E. Houngbo / *গিলবার্ট এফ হাউংবো* *(টোগো)।*
     ১ অক্টোবর, ২০২২ সালে তিনি দায়িত্ব গ্রহণ করেন।
 45) জাতিসংঘের কৃষি উন্নয়ন বিষয়ক তহবিল বা IFAD এর *বর্তমান প্রেসিডেন্ট Alvaro Lario / আলভারো
     নারিও (স্পেন)।* ১ অক্টোবর, ২০২২ সালে তিনি দায়িত্ব গ্রহণ করেন ৪ বছরের জন্য।
 46) D-8 এর বর্তমান মহাসচিব *Isiaka Abdulqadir Imam / ইসিয়াকা আবদুল কাদির ইমাম*
     (নাইজেরিয়া)। ১ জানুয়ারি, ২০২২ সালে তিনি দায়িত্ব গ্রহণ করেন।
 47) *IFRC/ICRC* এর বর্তমান প্রেসিডেন্ট *Mirjana Spoljaric Egger* (সুইজারল্যান্ড)। প্রথম
     নারী প্রেসিডেন্ট এবং ১ অক্টোবর, ২০২২ সালে তিনি দায়িত্ব গ্রহণ করেন।
 48) ৬ থেকে ১৮ নভেম্বর ২০২২ সালে ২৭তম জলবায়ু শীর্ষ সম্মেলন বা কপ-২৭ অনুষ্ঠিত হবে *শারম
     আল শেখ, মিশর।*
 49) ৬ থেকে ১৭ নভেম্বর ২০২৩ সালে ২৮তম জলবায়ু শীর্ষ সম্মেলন বা কপ-২৮ অনুষ্ঠিত হবে
     *সংযুক্ত আরব আমিরাতে।*
 50) ৪০ ও ৪১ তম আসিয়ান সম্মেলন অনুষ্ঠিত হবে ৮-১৩ নভেম্বর ২০২২ সালে নম পেন, কম্বোডিয়া।
 51) ইউক্রেনে রাশিয়ার নতুন সামরিক কমান্ডার *সের্গেই সুরুভিকিন*
 52) শহিদ ১৩৬ বা কামিকাজে ড্রোন ইরানের।
 53) *কুখ্যাত 'এভিন কারাগার'* ইরানে অবস্থিত। যেখানে ইরানের রাজনৈতিক বন্দী, সাংবাদিক ও
     বিদেশি নাগরিকদের বন্ধি করে রাখা হয়।
 54) *আব্দুল্লাহ নাদির সোমালিয়ার আল শাবাবের* সহ-প্রতিষ্ঠাতা ও প্রধান সমন্বয়ক ।
 55) হ্যারি পটার চলচ্চিত্রে হ্যাগ্রিড চরিত্র এবং আইটিভি গোয়েন্দা নাটক ক্র্যাকারে অভিনয় করা
     অভিনেতা রবি কোন্ট্রান ১ অক্টোবর, ২০২২ সালে মারা যান।
 56) *ইউসুফ আল-কারজাভি* খ্যাতিমান ইসলামি ব্যক্তিত্ব ও মুসলিম ব্রাদারহুডের আধ্যাত্মিক নেতা।
 57) ২৬-৩০ সেপ্টেম্বর *ফিলিপাইনের ম্যানিলায়* ADB - এর ৫৫ তম বার্ষিক সভা অনুষ্ঠিত হয়।
 58) ১০-১৬ অক্টোবর যুক্তরাষ্ট্রের ওয়াশিংটন ডিসিতে বিশ্বব্যাংক ও আন্তর্জাতিক মুদ্রা তহবিলের বার্ষিক
     সম্মেলন অনুষ্ঠিত হয়।
 59) ২০২২ সালের ১৫-১৬ নভেম্বর ১৭তম *G20 শীর্ষ সম্মেলন অনুষ্ঠিত হবে – বালি, ইন্দোনেশিয়া।*
 60) ২০২২ সালের ১৮-১৯ নভেম্বর ২৯তম *APEC শীর্ষ সম্মেলন অনুষ্ঠিত হবে – ব্যাংকক, থাইল্যান্ড।*
 61) ইসরায়েল এবং লেবানন যুক্তরাষ্ট্রের মধ্যস্থতায় এক ঐতিহাসিক সমুদ্রসীমা চুক্তিতে সই করেছে,
     যার ফলে দু'দেশের জন্যই সমুদ্রের তলদেশের বিরোধপূর্ণ গ্যাস ক্ষেত্রগুলো থেকে গ্যাস আহরণের
     পথ খুলে গেল। এই চুক্তিতে সই করেছেন *ইসরায়েলের প্রধানমন্ত্রী ইয়াইর লাপিদ এবং লেবাননের
     প্রেসিডেন্ট মিশেল আওন।*
 62) *ওমানের সোহার বন্দরকে* সংযুক্ত আরব আমিরাতের রাজধানী আবুধাবির সঙ্গে যুক্ত করতে *৩
     বিলিয়ন ডলারের* নতুন রেলপথ নির্মিত হতে যাচ্ছে। *৩০৩ কিলোমিটার (১৮৮ মাইল) দীর্ঘ
     রেলপথটি এখন নির্মাণাধীন।*
 63) বিশ্বব্যাপী খাদ্য সংকট মোকাবিলায় ক্ষতিগ্রস্ত দেশগুলোকে ঋণ সহায়তা দিতে *৩০০০ কোটি*
     ডলারের তহবিল গঠন করেছে বিশ্বব্যাংক ও আইএমএফ। এর মধ্যে বেশি ক্ষতিগ্রস্ত ও অতি
     দরিদ্র এমন দেশগুলোকে সুদবিহীন ঋণ দেওয়া হবে *৬৫০ কোটি ডলার।* ইউরোপীয় ইউনিয়নের
     ছোট ও দরিদ্র দেশগুলোকে দেওয়া হবে *১০০ কোটি ডলার।* এশিয়ার দেশগুলোও ওই তহবিল
     থেকে ঋণ পাবে। *এর মধ্যে বাংলাদেশও আলোচ্য তহবিল থেকে ঋণ পাবে।*
 64) আদালতের আদেশে ক্ষমতায় পুনর্বহাল হয়েছেন থাইল্যান্ডে ক্ষমতাচ্যুত প্রধানমন্ত্রী *প্রায়ুথ চান
     ওচা।* দেশটির সাংবিধানিক আদালত জানিয়েছে, সাময়িক বরখাস্ত হওয়া প্রায়ুথের মেয়াদ সীমা
     অতিক্রম না করায় ক্ষমতায় পুনর্বহাল হয়েছেন। *২০২৫ সাল* পর্যন্ত প্রধানমন্ত্রী পদে বহাল থাকবেন তিনি।
 65) জাতিসংঘের ট্রাইব্যুনাল হেগের আন্তর্জাতিক আদালতে *রুয়ান্ডা* গণহত্যার বিচার শুরু
     করেছে। *তুতসি জাতিগোষ্ঠীকে* নির্মূলে নেতৃত্ব দেওয়ার অপরাধে এই মামলার প্রধান অভিযুক্ত
     ব্যক্তি *ফেলিচিয়েন কানুজা,* যিনি তুতসি জনগোষ্ঠীকে হত্যার মাধ্যমে নির্মূল করার পরিকল্পনা
     করেছিলেন। এই গণহত্যায় প্রায় আট লাখ তুতসি ও উদারপন্থি হুতু জনগোষ্ঠীর মানুষকে প্রাণ
     দিতে হয়েছিল।
 66) সম্প্রতি যুক্তরাষ্ট্রের প্রেসিডেন্ট জো বাইডেন যুক্তরাষ্ট্র ও বিশ্বের শীর্ষ *সেমিকনডাক্টর
     উৎপাদনকারী ৩টি (তাইওয়ান, দক্ষিণ কোরিয়া ও জাপান) দেশকে* নিয়ে একটি জোট গড়তে
     উদ্যোগী হন। এটিকে বলা হচ্ছে *চিপ-৪ জোট।* এর উদ্দেশ্য হচ্ছে আমদানি নির্ভরতা কমানো ও
     চীনের প্রভাব খর্ব করা।
 67) রাশিয়ার মূল ভূখণ্ডের সঙ্গে ক্রিমিয়াকে যুক্ত করা কার্চ সেতুতে গত *৮ অক্টোবর বিস্ফোরণ ঘটে।*
     *২০১৮ সালের ১৫ মে কার্চ* সেতুর উদ্বোধন করেন পুতিন। ক্রিমিয়া উপদ্বীপের সঙ্গে রাশিয়াকে যুক্ত
     করা কার্ড *সেতুটি ১৯ কিলোমিটার দীর্ঘ।* সেতুটি রুশ প্রেসিডেন্ট ভ্লাদিমির পুতিনের অবকাঠামোগত
     উন্নয়ন প্রকল্পগুলোর শীর্ষে রয়েছে, রাজমুকুটের কোহিনুরের মতো।
 68) *২৮ সেপ্টেম্বর ১৯৪৭* শেখ হাসিনার জন্মদিন ।
 69) বর্তমানে দেশে মুক্তিযোদ্ধার স্বীকৃতি পাওয়া বীরাঙ্গনার *সংখ্যা ৪৪৮ জন।*
 70) দেশের প্রথম নারী সচীব _খোদেজা আজম।_
 71) দেশের প্রথম নারী সিনিয়র অর্থসচিব হিসেবে নিয়োগ পান *ফাতিমা ইয়াসমিন।*
 72) অর্থনৈতিক সম্পর্ক বিভাগের (ERD) দ্বিতীয় নারী সচিব- শরিফা খান।
 73) ক্ষুদ্র নৃ-গোষ্ঠীর প্রথম নারী ডিসি (জামালপুর) - শ্রাবস্তী রায়।
 74) জুন ২০২২ পর্যন্ত বাংলাদেশের শান্তিরক্ষী সদস্যরা অংশগ্রহণ করেছে ৪৩টি দেশের ৫৫টি মিশনে।
 75) জাতিসংঘে বাংলাদেশের নতুন স্থায়ী প্রতিনিধি - মোহাম্মদ আব্দুল মুহিত।
 76) দেশের প্রথম এক্সপ্রেসওয়ের নাম - জাতির পিতা বঙ্গবন্ধু শেখ মুজিবুর রহমান মহাসড়ক।
 77) *'জেকে ১৯৭১' চলচ্চিত্রটির নির্মাতা ফাখরুল আরেফিন খান।*
 78) *ফাখরুল আরেফিন খান যে নামে খ্যাত ভুবন মাঝি।*
 79) ২০২২ সালে সরকারি অনুদানপ্রাপ্ত চলচ্চিত্রে সংখ্যা - ১৯টি।
 80) ২০২১-২২ অর্থবছরে সরকারি অনুদানপ্রাপ্ত মুক্তিযুদ্ধভিত্তিক দুইটি চলচ্চিত্র - 'জয় বাংলার ধ্বনি' ও
     'একাত্তর-করতলে ছিন্নমাথা'।
 81) *"জয় বাংলার ধ্বনি'* চলচ্চিত্রের পরিচালক *মোহাম্মদ খোরশেদুল আলম খন্দকার* । *“একাত্তর-করতলে ছিন্নমাথা'*
     চলচ্চিত্রের *পরিচালক রফিকুল আনোয়ার (রাসেল)।*
 82) দেশের প্রথম 'শেখ কামাল আইটি বিজনেস ইনকিউবেটর' উদ্বোধন করা হয়- চট্টগ্রাম প্রকৌশল ও প্রযুক্তি বিশ্ববিদ্যালয়ে।
 83) দেশের ৬১তম তফসিলি ব্যাংক সিটিজেনস ব্যাংক।
 84) ২০২২ সালে যে দেশের সাথে বাংলাদেশের ভিসা অব্যাহতি চুক্তি কার্যকর হয় - ওমান।
 85) দেশের প্রথম ছয় লেন বিশিষ্ট কালনা সেতু যে নদির উপর নির্মিত - মধুমতি।
 86) ইউরোপীয় ইউনিয়নের দেশসমূহে বাংলাদেশ শুল্কমুক্ত রপ্তানি সুবিধা পাবে ২০২৯ সাল পর্যন্ত।
 87) ন্যাশনাল জুডিশিয়াল একাডেমি প্রতিষ্ঠিত হবে - শিবচর, মাদারীপুর।
 88) দেশের প্রথম হাউজিং বন্ড চালু করতে যাচ্ছে ব্র্যাক ব্যাংক লিমিটেড ও
     International Finance Corporation (IFC) যৌথভাবে।
 89) এ পর্যন্ত অর্থনৈতিক অঞ্চলের অনুমোদন দেয়া হয়েছে ৯৭টি (২৮টির নির্মাণ কাজ চলছে)।
 90) বিশ্বের দ্বিতীয় সর্বোচ্চ পর্বতশৃঙ্গ K2'র চূড়া বিজয়ী প্রথম বাংলাদেশি - ওয়াসফিয়া নাজরীন।
 91) এ বছর *বঙ্গবন্ধু কূটনৈতিক উৎকর্ষ পদক* লাভ করেন- *সুলতানা লায়লা হোসেন (বাংলাদেশ) ও ইতো নাওকি (জাপান)।*
 92) প্রথমবারের মতো কৃষিক্ষেত্রে গুরুত্বপূর্ণ ব্যক্তি (AIP) সম্মাননা লাভ করেন - ১৩ জন।
 93) *ছত্রাকজনিত রোগ প্রতিরোধী ও উচ্চফলনশীল জাতের ৫টি সরিষা উদ্ভাবন* করেছেন - বাংলাদেশ কৃষি বিশ্ববিদ্যালয়ের
     *গবেষক ড. আরিফ হাসান খান রবিন ও তার দল।*
 94) দেশের প্রথম সুপার স্পেশালাইজ হাসপাতাল অবস্থিত শাহবাগ, ঢাকা। 
 95) দেশের প্রথম ধান জাদুঘর অবস্থিত বাংলাদেশ ধান গবেষণা ইনস্টিটিউট (BRRI), গাজীপুর।
 96) ২০২২ সালে পুলিৎজার পুরস্কার লাভ করেন যে বাংলাদেশি - চিত্রশিল্পী ফাহমিদা আজিম।
 97) প্রথম বাংলাদেশি হিসেবে পুলিৎজার পুরস্কার লাভ করেন আলোকচিত্রী পনির হোসেন (২০১৮ সাল)।
 98) বিশ্ব ডায়াবেটিক ফেডারেশনের প্রথম গ্লোবাল অ্যাম্বাসেডর হতে যাচ্ছেন (ডিসেম্বরে) প্রধানমন্ত্রী শেখ হাসিনা।
 99) স্মার্ট বাংলাদেশ টাস্কফোর্স-এর চেয়ারপারসন মাননীয় প্রধানমন্ত্রী।
 100) Detailed Area Plan (DAP)-এর আয়তন ১,৫২৮ বর্গকিমি বা ৫৯০ বর্গমাইল।
 101) বাংলাদেশ যে দেশের সাথে Comprehensive Economic z Partnership Agreement (CEPA) সাক্ষর করতে
      যাচ্ছে - ভারত।
 102) বাংলাদেশ সরকার যে প্রকল্পের অধীনে গৃহহীন এবং বাস্তুচ্যুত মানুষদের জন্য বাসস্থান নির্মাণ করে দেয় *আশ্রয়ণ প্রকল্প।*
 103) দেশের প্রথম পূর্ণাঙ্গ বেসরকারি মহাকাশ গবেষণাকেন্দ্র অবস্থিত শ্রীপুর, গাজীপুর।
 104) বাংলাদেশের পাখি তালিকায় যুক্ত হওয়া নতুন পাখি – উদয়ী জিরিয়া।
 105) 'মাদার অব হিউম্যানিটি সমাজকল্যাণ পদক' নীতিমালা'র নাম পরিবর্তন করে যে নামকরন করার প্রস্তাব
      অনুমোদিত হয়েছে - 'জাতীয় মানবকল্যাণ পদক নীতিমালা'।
 106) *বাংলাদেশ পুলিশের ৩১তম মহাপরিদর্শক (আইজি) হিসেবে দায়িত্ব গ্রহণ করেন চৌধুরী আবদুল্লাহ আল-মামুন।*
 107) *র‍্যাপিড অ্যাকশন ব্যাটালিয়নের (র‍্যাব) বর্তমান মহাপরিচালক - এম খুরশীদ হোসেন।*
 108) দেশের বিশিষ্ট শিশুরোগ বিশেষজ্ঞ, নারী ও শিশু স্বাস্থ্যকেন্দ্র'র বোর্ড অব ট্রাস্টির চেয়ারম্যান এবং
      প্রতিষ্ঠানটির প্রতিষ্ঠাতা পরিচালক অধ্যাপক *ডা. এম কিউ কে তালুকদারকে জাতীয় অধ্যাপক হিসেবে
      নিয়োগ দিয়েছে সরকার।*
 109) রামপাল তাপবিদ্যুৎ কেন্দ্রের উৎপাদন ক্ষমতা – ১৩২০ মেগাওয়াট।
 110) বঙ্গবন্ধুর 'অসমাপ্ত আত্নজীবনী' সর্বশেষ অনূদিত হয় - ত্রিপুরা ভাষায় (ককবরক)। দ্বিতীয় সর্বশেষ - থাই ভাষায়।
 111) বঙ্গবন্ধু শেখ মুজিব মেডিকেল বিশ্ববিদ্যালয় (বিএসএমএমইউ) সুপার স্পেশালাইজড হাসপাতাল দেশের প্রথম
      সুপার স্পেশালাইজড হাসপাতাল অবস্থিত- শাহবাগ, ঢাকা।
 112) সাধারণ জনগণের অংশগ্রহণমূলক সরকার ও শাসন ব্যবস্থা নিশ্চিত করতে জনগন-সরকার সম্পৃক্ততা বা
      সেতু বন্ধন তৈরির প্ল্যাটফর্ম - “জনতার সরকার” (সরকারি ওয়েব পোর্টাল)।
 113) ঘুমধুম ও তুমব্রু সীমান্ত অবস্থিত - বান্দরবানের নাইক্ষ্যংছড়িতে।
 114) বিশ্বব্যাংকের অর্থায়নে বর্তমানে চলমান প্রকল্প - ৫৫টি।
 115) মেট্রোরেল আনুষ্ঠানিকভাবে যাত্রা শুরু করবে - ১৬ ডিসেম্বর, ২০২২।
 116) জাতীয় কৃষি কাউন্সিলের সভাপতি প্রধানমন্ত্রী।
 117) ২০২১-২০২২ অর্থবছরে বাংলাদেশ থেকে *পণ্য রপ্তানি হয় ২০৩টি দেশ বা অঞ্চলে* এর মধ্যে *ঘাটতি
      রয়েছে ৯১টি দেশের সাথে* আর *অনুকূলে রয়েছে ১১২টি দেশ।*
 118) ৪৪তম মস্কো আন্তর্জাতিক চলচিত্র উৎসবে বিশেষ জুরি পুরস্কার সিলভার সেন্ট জর্জ অ্যাওয়ার্ড লাভ করে
      বাংলাদেশি চলচিত্র - আদিম (পরিচালক যুবরাজ শামীম)।
 119) সরকারি অনুদানে নির্মিত শিশুতোষ চলচ্চিত্র - *রাসেলের জন্য অপেক্ষা।* *সেলিনা হোসেনের উপন্যাস* অবলম্বনে
      নির্মিত চলচিত্রটি পরিচালনা করেন *নূর-ই আলম।*
 120) *শেখ আব্দুল হাকিম স্বাধীন বাংলা ফুটবল দলের অন্যতম সদস্য* ২৮ আগস্ট ২০২২ সালে মৃত্যুবরণ করেন।
 121) ঢাকা পৌরসভার প্রথম নির্বাচিত *মেয়র ব্যারিস্টার আবুল হাসনাত।*
 122) প্রবাসী কল্যাণ ও বৈদেশিক কর্মসংস্থান মন্ত্রণালয়ের ওয়েজ আর্নার্স কল্যাণ বোর্ড '১৬১৩৫' টোল ফ্রি নম্বর দিয়ে
      'প্রবাস বন্ধু কল সেন্টার নামে হটলাইন চালু করেছে।
 123) কমনওয়েলথের কার্যনির্বাহী ও অ্যাক্রেডিটেশন কমিটির সদস্য নির্বাচিত হয়েছে বাংলাদেশ। এ দুই কমিটিতে
      বাংলাদেশের প্রতিনিধিত্ব করবেন যুক্তরাজ্যে বাংলাদেশের হাইকমিশনার ও কমনওয়েলথ বোর্ড অব গভর্নরসের
      সদস্য সাইদা মুনা তাসনিম। বাংলাদেশ সর্বসম্মতিক্রমে ২০২২-২৪ মেয়াদের জন্য কমনওয়েলথ বোর্ড অব গভর্নরদের
      নির্বাহী কমিটির (এক্সকো) সদস্য নির্বাচিত হয়েছে। এছাড়া বাংলাদেশ ২০২২-২৩ মেয়াদের জন্য সর্বসম্মতিক্রমে
      কমনওয়েলথ অ্যাক্রেডিটেশন কমিটির সদস্য নির্বাচিত হয়েছে।
 124) *বাংলাদেশের আনন্দ শিপইয়ার্ডে তৈরি ৬১০০ টন ধারণক্ষমতা* সম্পন্ন কন্টেইনার জাহাজ জন্য করেছে
      যুক্তরাজ্যের প্রতিষ্ঠান *এনজিয়ান শিপিং কোম্পানি লিমিটেড।*
 125) তুরস্কের বর্তমান নাম তুর্কিয়ে।
 126) গাড়িতে স্থাপন করা উচ্চপ্রযুক্তির রকেট লঞ্চার হিমার্স যে দেশের তৈরি - যুক্তরাষ্ট্র।
 127) ওয়ানডে ক্রিকেটে সর্বোচ্চ ৪৯৮ রানের রেকর্ড গড়ে যে দেশ ইংল্যান্ড। (বিপক্ষ নেদারল্যান্ডস)
 128) সংযুক্ত আরব আমিরাত ও ইসরায়েলের মধ্যে মুক্ত বাণিজ্য চুক্তি স্বাক্ষরিত হয় - ৩১ মে ২০১২।
 129) জাতিসংঘ নিরাপত্তা পরিষদের নতুন অস্থায়ী সদস্য নির্বাচিত হয় *ইকুয়েডর, জাপান, মাল্টা, মোজাম্বিক ও সুইজারল্যান্ড।* 
 130) IPMDA'র পূর্ণরূপ - *Indo-Pacific Partnership for Maritime Domain Awareness.*
 131) সমুদ্র অর্থনীতি (Blue Economy) ধারণাটির প্রবর্তক - গুন্টার পলি; ২০১০ সালে।
 132) কলম্বিয়ার প্রথম কৃষ্ণাঙ্গ নারী ভাইস প্রেসিডেন্টের নাম – ফ্রান্সা মার্কেজ।
 133) ২০২৬ সালের ২৩তম বিশ্বকাপ ফুটবল অনুষ্ঠিত হবে - ১৬টি শহরে।
 134) জাতিসংঘের সাধারণ পরিষদের ৭৭তম অধিবেশনের সভাপতি - কাসাবা কোরেসি (হাঙ্গেরি)।
 135) যে দেশের কাছে সর্বাধিক পারমাণবিক অস্ত্র রয়েছে - রাশিয়া।
 136) ২০২২ সালের কাতার বিশ্বকাপে *শেষ দল হিসেবে সূযোগ পায় - কোস্টারিকা।*
 137) বাংলাদেশের বর্তমান টেস্ট অধিনায়ক সাকিব আল হাসান।
 138) ইউক্রেনকে সহায়তার জন্য নোবেল পুরস্কার বিক্রি করে ১০৩.৫ মিলিয়ন মার্কিন ডলার ইউনিসেফকে
      দিয়েছেন *রাশিয়ার সাংবাদিক দিমিত্রি মুরাতভ।*
 139) IPEF এর পূর্ণরূপ - *Indo-Pacific Economic Framework for Prosperity.*
 140) শ্রীলংকার পূর্বনাম ছিল সিলোন।
 141) ভারতের প্রথম আদিবাসী প্রেসিডেন্ট দ্রৌপদী মুর্মু যে সম্প্রদায়ের সাঁওতাল।
 142) উন্মুক্ত বলকান এর সদস্য দেশ তিনটি – আলবেনিয়া, উত্তর মেসিডোনিয়া ও সার্বিয়া।
 143) Partners in the Blue Pacific (PBP) ভুক্ত পাঁচটি দেশ – যুক্তরাষ্ট্র, যুক্তরাজ্য, অস্ট্রেলিয়া, জাপান ও নিউজিল্যান্ড।
 144) চীনকে মোকাবিলায় বৈশ্বিক অবকাঠামো ও বিনিয়োগ অংশীদ্বারিত্ব (PGII) প্রকল্প গ্রহণ করে যে সংস্থা - G7
 145) ১৯-২১ মে ২০২৩, ৪৯তম G-7 শীর্ষ সম্মেলন অনুষ্ঠিত হবে যে শহরে - হিরোশিমা, জাপান।
 146) ওডেসা যে দেশের সমুদ্র বন্দর - ইউক্রেন।
 147) সম্প্রতি ইরান যে মুদ্রাকে বিনিময়যোগ্য মুদ্রা হিসেবে তালিকাভুক্ত করে রাশিয়ান রুবল।
 148) শ্রীলংকার বর্তমান প্রেসিডেন্ট রনিল বিক্রমাসিংহে।
 149) শ্রীলংকার বর্তমান প্রধানমন্ত্রী – দিনেশ গুনাবর্ধনে।
 150) ২০২৪ সালে ২৭তম কমনওয়েলথ শীর্ষ সম্মেলন অনুষ্ঠিত হবে সামোয়া।
 151) ২৪-২৫ জুন ২০২২ ২৬তম কমনওয়েলথ শীর্ষ সম্মেলন অনুষ্ঠিত হয় – কিগালি, রুয়ান্ডা।
 152) কমনওয়েলথ এর বর্তমান সদস্য দেশ - ৫৬টি।
 153) ২৫ জুন ২০২২ কমনওয়েলথের ৫৫ ও ৫৬ তম সদস্য দেশ হিসেবে সদস্যপদ লাভ করে যথাক্রমে- গ্যাবন ও টোগো।
 154) ব্রিটিশ শাসনাধীন না হয়েও কমনওয়েলথের সদস্যদেশ চারটি মোজাম্বিক, গ্যাবন, রুয়ান্ডা ও টোগো।
 155) ICSID এর বর্তমান সদস্য দেশ - ১৫৭টি (সর্বশেষ কিরগিজিস্তান)।
 156) ইসরায়েলের বর্তমান প্রধানমন্ত্রী ইয়ার লাপিদ।
 157) ২০২২ সালে যে দুটি দেশ ব্রিকসের সদস্যপদের জন্য আবেদন করে - আর্জেন্টিনা ও ইরান।
 158) Abenomics এর প্রবক্তা - শিনজো আবে (জাপান)।
 159) মুদ্রাস্ফীতি নিয়ন্ত্রণে বাজারে 'স্বর্ণমুদ্রা' চালু করে যে দেশ - জিম্বাবুয়ে।
 160) মঙ্গল গ্রহের প্রথম পূর্ণাঙ্গ ত্রিমাত্রিক মানচিত্র তৈরি করেছে যে মহাকাশযান - তিয়ানওয়েন-১ (চীন)।
 161) ম্যানগ্রোভ রয়েছে বিশ্বের ১১৮টি দেশে।
 162) DBID'র পূর্ণরূপ — Digital Business Identification (DBID),
 163) PGI'র পূর্ণরূপ - Partnership for Global Infrastructure and Investment.
 164) ২৩তম কমনওয়েলথ গেমস অনুষ্ঠিত হবে - ১৭-২৯ মার্চ ২০২৬ (ভ্যানু - ভিক্টোরিয়া, অস্ট্রেলিয়া)।
 165) চীনের 'বেল্ট অ্যান্ড রোড ইনিশিয়েটিভ' (বিআরআই) এর পাল্টা ব্যবস্থা হিসেবে G-7 যে পরিকল্পনা হাতে নিয়েছে
      - "দ্য পার্টনারশিপ ফর গ্লোবাল ইনফ্রাস্ট্রাকচার অ্যান্ড ইনভেস্টমেন্ট' (PGII).
 166) ইউরোপের বৃহত্তম পারমাণবিক বিদ্যুৎকেন্দ্র জাপোরিঝিয়া পারমাণবিক বিদ্যুৎকেন্দ্র।
 167) ২৫ জুলাই, ২০২২ ক্রমবর্ধমান মুদ্রাস্ফীতি নিয়ন্ত্রণে বাজারে স্বর্ণমুদ্রা ছাড়ে জিম্বাবুয়ে।
 168) বিশ্বের সর্বোচ্চ রেল সেতু চেনাব সেতু (ভারত)।
 169) (১ মে ২০২২ Resilience and Sustainability Trust (RST) প্রতিষ্ঠা করে আন্তর্জাতিক মুদ্রা তহবিল (IMF).
 170) মির (Mir) পেমেন্ট কার্ড যে দেশভিত্তিক রাশিয়া।
 171) সম্প্রতি যে দেশ নিষিক্ত ডিম্বাণু-শুক্রাণু ছাড়াই ভ্রুণ তৈরি করেছে - ইসরায়েল।
 172) দক্ষিণ কোরিয়া চাঁদের কক্ষপথে যে অরবিটার উৎক্ষেপণ করে দানুরি (Danuri).
 173) ডলার বা অন্য কোনো হার্ড কারেন্সিকে (প্রধান আন্তর্জাতিক মুদ্রাসমূহ) এড়িয়ে ২টি দেশ নিজ নিজ
      মুদ্রায় বাণিজ্য করলে সেটাকে আর্থিক পরিভাষায় বলা হয় - কারেন্সি সোয়াপ বা মুদ্রাবিনিময়।
 174) IMF এর নির্বাহী পরিষদের সদস্য সংখ্যা ২৪টি এবং অস্থায়ী সদস্য ১৬টি।
 175) ১৫-১৬ নভেম্বর ২০২২ ১৭তম G20 শীর্ষ সম্মেলন অনুষ্ঠিত হবে বালি, ইন্দোনেশিয়া।
 176) ২০২৩ সালে ১৮তম G20 শীর্ষ সম্মেলন অনুষ্ঠিত হবে - জম্মু এবং কাশ্মীর, ভারত।
 177) কাতার বিশ্বকাপ ফুটবল শুরু হতে যাচ্ছে ২০ নভেম্বর ২০২২।
 178) ২০২৪ সালে আন্তর্জাতিক মহাকাশ স্টেশন (ISS) ছেড়ে যাওয়ার সিদ্ধান্ত নেয় যে দেশ - রাশিয়া।
 179) OPEC'র নতুন মহাসচিব হাইথাম আল-গাইস (কুয়েত)।
 180) আন্তর্জাতিক মুদ্রা তহবিলের (IMF) প্রধান অর্থনীতিবিদ - পিয়েরে-অলিভিয়ের গৌরিঞ্চাস।
 181) বিশ্বব্যাংকের প্রধান অর্থনীতিবিদ - ইন্দরমিত গিল।
 182) AIIB (Asian Infrastructure Investment Bank) বর্তমান সদস্য দেশ ৯২টি (সর্বশেষ – ইরাক)।
 183) আন্তর্জাতিক ক্রিকেট কাউন্সিলের (ICC) বর্তমান সদস্য দেশ – ১০৮টি।
 184) ২০২৪ সালে আইসিসি নারী টি-২০ বিশ্বকাপ অনুষ্ঠিত হবে বাংলাদেশে।
 185) ইউরোপের খরা পর্যবেক্ষণকারী সংস্থার নাম - European Drought Observatory (EDO).
 186) RTA এর পূর্ণরূপ — Regional Trade Agreement. 
 187) যুক্তরাজ্যের প্রথম নারী প্রধানমন্ত্রী মার্গারেট থ্যাচার।
 188) ভারতের বিমানবাহী প্রথম রণতরীর নাম - আইএনএস বিক্রান্ত।
 189) যুক্তরাষ্ট্রের মর্যাদাপূর্ণ পুরস্কার এমি এওয়ার্ড' লাভ করেন সাবেক মার্কিন প্রেসিডেন্ট বারাক ওবামা।
 190) সাংহাই সহযোগীতা সংস্থার (SCO) প্রথম সাংস্কৃতিক ও পর্যটন রাজধানী বানারসি (ভারত)।
 191) ১৩ সেপ্টেম্বর ২০২২ সালে জাতিসংঘের সাধারণ পরিষদের (UNGA) এর ৭৭ তম অধিবেশন অনুষ্ঠিত হয়।
 192) এশিয়া কাপ ক্রিকেট টুর্নামেন্টর ১৫ তম আসরে চ্যাম্পিয়ন হয় – শ্রীলংকা। রানারআপ পাকিস্তান।
 193) ষষ্ঠ নারী সাফ চ্যাম্পিয়ন বাংলাদেশ। সেরা খেলোয়ার সাবিনা খাতুন।
 194) *২০২১-২০২২ মৌসুমের উয়েফা বর্ষসেরা পুরুষ খেলোয়াড় করিম বেনজেমা।*
 195) ইরানের সাথে সব ধরনের কূটনৈতিক সম্পর্ক ছিন্ন করার ঘোষণা দিয়েছে ন্যাটোভুক্ত মুসলিম দেশ - আলবেনিয়া।
 196) রাশিয়ার ১০২ তম সামরিক ঘাঁটি অবস্থিত - *আর্মেনিয়ার জিউমরিতে।*
 197) *ইউএস ওপেন নারী এককে চ্যাম্পিয়ন পোল্যান্ডের মহিলা টেনিস নক্ষত্র ইগা সুয়াটেক।*
 198) *অস্ট্রেলিয়ান ওপেন নারী এককে চ্যাম্পিয়ন অস্ট্রেলিয়া মহিলা টেনিস নক্ষত্র  Ashleigh Barty।*
 199) *ইউএস ওপেন পুরুষ এককে চ্যাম্পিয়ন স্পেনিশ কার্লোস আলকারাজ (উপন)।*
 200) *অস্ট্রেলিয়ান ওপেন পুরুষ এককে চ্যাম্পিয়ন স্পেনিশ রাফায়েল নাদাল।*
 201) যুক্তরাজ্যের প্রথম *নারী উপপ্রধানমন্ত্রী থেরেসে কফি।*
 202) যুক্তরাজ্যের পরিবর্তিত জাতীয় সংগীতের শিরোনাম God Save the King (ঈশ্বর রাজাকে রক্ষা করুন)
 203) যুক্তরাজ্যের নতুন রাজা তৃতীয় চার্লসের স্ত্রী *ক্যামিলার রাজকীয় মর্যাদা – কুইন কনসার্ট।*
 204) চীন প্রথম মুখ দিয়ে শ্বাস (ইনহেলার) নেওয়ার করোনার টাকা আবিষ্কার করে।
 205) বর্তমান বিশ্বের দীর্ঘতম ক্ষমতাসীন শাসক - *ব্রুনাইয়ের সুলতান হাসানাল বলকিয়া।*
 206) জাতিসংঘের মানবাধিকার বিষয়ক *হাইকমশনার ভলকার তুর্ক (অস্ট্রিয়া)।*
 207) জাতিসংঘের বর্তমান *পুলিশ প্রধান লুইস লিবেরিও কারিলহো।*
 208) ৫-৮ সেপ্টেম্বর Eastern Economic Forum এর বৈঠক অনুষ্ঠিত হয় ভ্লাদিভস্তক, রাশিয়া।
 209) ২৬-৩০ সেপ্টেম্বর IAEA এর সাধারণ সভা অনুষ্ঠিত হয় - ভিয়না, অস্ট্রিয়া।
 210) ১২-১৪ সেপ্টেম্বর 'International Association of Police Academies (INTERPA) এর ১১তম
      সম্মেলন অনুষ্ঠিত হয় ঢাকা, বাংলাদেশ। এই সম্মেলনে বাংলাদেশ ও কাতার INTERPA এর ভাইস প্রেসিডেন্ট
      নির্বাচিত হয়। প্রতিপাদ্য ছিল - Digitalization of Policing. INTERPA বিশ্বের বিভিন্ন দেশের পুলিশ
      প্রশিক্ষণ একাডেমি নিয়ে গঠিত। এর সদস্য সংখ্যা ৫৯টি দেশের ৭৬টি পুলিশ প্রশিক্ষণ একাডেমি এবং
      সদরদপ্তর- আঙ্কারা, তুরস্ক।
 211) *হিলারি ম্যান্টেল যুক্তরাজ্যের বিখ্যাত সাহিত্যিক।* তিনিই প্রথম ব্রিটিশ নারী সাহিত্যিক যিনি ২বার বুকার পুরস্কার পায়।
      *২০০৯ সালে Wolf Hall ও ২০১২ সালে Bring Up the Bodies* এর জন্য বুকার পুরস্কার পায়।
 212) *৮ সেপ্টেম্বর ২০২২ সালে রাজা তৃতীয় চার্লস ৫৬টি স্বাধীন দেশের জোট কমনওয়েলথের* নতুন প্রধান হন।
 213) যুক্তরাজ্যের ক্যামব্রিজ বিশ্ববিদ্যালয়ের গবেষকেরা বিশ্বের প্রথম কৃত্রিম গ্রুপ সিনথেটিক এমব্রায়ো তৈরি করেন।
 214) ২০১৯ সালে বিদায়ী প্রেসিডেন্ট নুরসুলতান নাজারবায়েভের সম্মানে রাজধানীর নাম 'আস্তানা' বদলে 'নূর-সুলতান' নামকরণ করা হয়েছিল।
      গত ১৬ সেপ্টেম্বর ২০২২ পার্লামেন্টে সর্বসম্মতিক্রমে পাস হওয়া সংবিধান সংশোধন করে দেশটির রাজধানীর নাম পুনরায় 'আস্তানা' করা হয়।
 215) ক্রীড়ার সর্বোচ্চ আদালত বা *‘দ্য কোর্ট অব আরবিট্রেশন ফর স্পোর্টস’ (সিএএস)*
 216) চিলি ইকুয়েডরের যে খেলোয়াড়কে নিয়ে আপত্তি তুলেছিল, সেই *বায়রন কাস্তিলোকে ইকুয়েডরের নাগরিক* বলে গণ্য করেছেন
     আন্তর্জাতিক ক্রীড়া আদালত (সিএএস)।
 217) টি টুয়েন্টি বিশ্বকাপের ফাইনালের ম্যান অফ দ্যা ম্যাচ *শ্যাম কারেন ।*
 218) তাইওয়ান উপদ্বীপ ঘিরে *চীনের পিপলস লিবারেশন আর্মির (পিএলএ)* সেনা সমাবেশ অনেক বেড়েছে।
 219) ইরানে মৃত্যুদণ্ড দেওয়া ওই বিক্ষোভকারীর নাম *মহসেন সেকারি* বলে উল্লেখ করা হয়েছে
 220) মুখ্য সচিব পদে *তোফাজ্জল হোসেন মিয়া* মুখ্য সচিব পদে স্থলাভিষিক্ত হয়েছেন।
 221) *কবির বিন আনোয়ার মন্ত্রিপরিষদ সচিব* ।
 222) *আরাকানে জুলাই থেকে শুরু হওয়া যুদ্ধ* থামাতে রাজি হলো মিয়ানমারের সশস্ত্র বাহিনী ও 
        আরাকান আর্মি। এই যুদ্ধবিরতিতে মধ্যস্থতাকারী হিসেবে জাপানের *ইউহেই সাসাকাওয়ার* 
        উপস্থিতি দক্ষিণ এশিয়াজুড়ে বিশেষ নজর কাড়ল।
 223) *ইউহেই সাসাকাওয়া* নিপ্পন ফাউন্ডেশন ও সাসাকাওয়া পিস ফাউন্ডেশনের চেয়ারম্যান।
 224) বিশ্বকাপ  ফুটবলের সেমিফাইনাল, ফাইনালের বলের নাম *‘আল হিল্‌ম’*
 225) *বিশ্বকাপে কোয়ার্টার ফাইনাল পর্যন্ত* প্রতিটি ম্যাচ অনুষ্ঠিত হয়েছে অফিশিয়াল বল 
     *‘আল রিহলা’* দিয়ে।
 226) *‘আল রিহলা’ শব্দের অর্থ ছিল সফর।*
 227) *আল হিল্‌মের অর্থ—স্বপ্ন।*
 228) ইসরায়েল এবং লেবানন যুক্তরাষ্ট্রের মধ্যস্থতায় এক ঐতিহাসিক সমুদ্রসীমা চুক্তিতে সই করেছে,
      যার ফলে দু'দেশের জন্যই সমুদ্রের তলদেশের বিরোধপূর্ণ গ্যাস ক্ষেত্রগুলো থেকে গ্যাস আহরণের পথ খুলে গেল।
 229) পরীক্ষাগারে তৈরি রক্ত প্রথমবারের মতো মানবশরীরে পরীক্ষা করে দেখলেন
      যুক্তরাজ্যের গবেষকেরা। তাঁরা বলছেন, রক্তের নানা সমস্যা সমাধানে তাঁদের
      এই গবেষণা কাজে লাগবে। এ ছাড়া বিরল রক্তের গ্রুপসহ বিভিন্ন চিকিৎসায়
      পরীক্ষাগারে তৈরি রক্ত ব্যবহার করা যাবে। টুইটারের মালিক ও প্রধান
      নির্বাহী কর্মকর্তা ইলন মাস্ক।
 230) বিশ্বের সর্ববৃহৎ যাত্রীবাহী ট্রেন চালু করল সুইজারল্যান্ড। এ যাত্রীবাহী
      ট্রেনে ছিল ১০০ বগি। পরপর ১০০ বগির কারণে ১ দশমিক ৯ কিলোমিটার লম্বা
      ছিল ট্রেনটি। আলপ্স পর্বতমালার ওপর দিয়ে ২৫ কিলোমিটার পথ পাড়ি দিয়েই
      রেকর্ড গড়ে ফেলেছে ট্রেনটি।
 231) বিশ্বের ৮০০ কোটিতম শিশুর জন্ম ফিলিপাইনে। দেশটির রাজধানী ম্যানিলার
      তোন্দো শহরে জন্ম নেয় এক কন্যাশিশু। বিশ্বের ৮০০ কোটিতম মানুষ (প্রতিকী)
      হিসেবে ধরা হচ্ছে। *শিশুটির নাম রাখা হয়েছে ভিনিস মাবাসাং।* ম্যানিলার
      *ডক্টর জোস ফাবেলা মেমোরিয়াল নামক হাসপাতালে স্থানীয় সময় রাত ১টা ৩০
      মিনিটে ভিনিস মাবাসাংয়ের জন্ম হয়।*
 232) পাকিস্তানের নতুন সেনাপ্রধান হিসাবে দায়িত্ব নিলেন *জেনারেল সৈয়দ আসিম
      মুনির আহমদ।*
 233) নিজেদের জ্বালানিনিরাপত্তা নিশ্চিত করার ক্ষেত্রে আরও কয়েক ধাপ এগিয়ে
      গেল চীন। কাতারের কোম্পানি *কাতার এনার্জির সঙ্গে ২৭ বছরের জন্য এলএনজি
      বা তরলীকৃত প্রাকৃতিক গ্যাস কেনার চুক্তি করেছে চীনের কোম্পানির সিনোপেক।*
      তরলীকৃত প্রাকৃতিক গ্যাসের (এলএনজি) চুক্তির ইতিহাসে এটি সবচেয়ে
      দীর্ঘমেয়াদি।
 234) ইসরায়েলের নতুন প্রধানমন্ত্রী *বেনিয়ামিন নেতানিয়াহু।*
 235) *পেরুর প্রেসিডেন্ট পেদ্রো কাস্তিলো সংস্কৃতিমন্ত্রী বেটসি শাভেজকে দেশের নতুন
      প্রধানমন্ত্রী হিসেবে ঘোষণা করেছেন।* প্রেসিডেন্ট হিসেবে দায়িত্ব গ্রহণের
      ১৬ মাসের মধ্যে এ নিয়ে পঞ্চম প্রধানমন্ত্রীর নাম ঘোষণা করলেন সংকটে পড়া
      পেরুর প্রেসিডেন্ট।
 236) *ICSID এর বর্তমান সদস্য দেশ ১৫৮টি। ২১ অক্টোবর ২০২২ সালে এঙ্গোলা ১৫৮তম
      দেশের মর্যাদা লাভ করে।*
 237) দক্ষিণ পূর্ব এশিয়ার নেতারা ১০-জাতির আসিয়ান আঞ্চলিক ব্লকে ১১তম দেশ
      হিসেবে পূর্ব তিমুরকে যোগদানের সম্মত হয়েছে। স্বাগতিক কম্বোডিয়ায় আয়োজিত
      এক শীর্ষ সম্মেলনের প্রকাশিত এক বিবৃতিতে এ কথা জানানো হয়েছে।
 238) *১৫-১৬ নভেম্বর ইন্দোনেশিয়ার বালিতে বিশ্বের ২০টি বৃহৎ অর্থনীতির দেশের
      জোট জি-২০ এর ১৭তম সম্মেলন অনুষ্ঠিত হয়।*
 239) *৯-১০ সেপ্টেম্বর ২০২৩ সালে ১৮তম জি-২০ সম্মেলন অনুষ্ঠিত হবে ভারতের নয়া
      দিল্লীতে।*
 240) *বিশ্বকাপ অভিষেকে সবচেয়ে কম বয়সে গোলের রেকর্ড গড়লেন পাবলো মার্টিন
      গাভি।* স্পেনের সর্বকনিষ্ঠ খেলোয়াড় হিসেবে বিশ্বকাপে খেলার রেকর্ডটিও
      তার।
 241) *বিশ্বকাপের ইতিহাসে প্রথম ফুটবলার হিসেবে পাঁচটি বিশ্বকাপে গোল করার
      নজির গড়লেন ক্রিস্টিয়ানো রোনালদো।* জার্মানিতে ২০০৬ সালের বিশ্বকাপে
      প্রথমবার অংশ নিয়েছিলেন রোনালদো। ইরানের বিপক্ষে পেনাল্টি থেকে
      বিশ্বকাপে নিজের প্রথম গোল পান রোনালদো।
 242) কেমব্রিজ ডিকশনারির ওয়ার্ড অদ দ্য ইয়ার ২০২২ হয়েছে হোমার ( Homer) শব্দটি।
 243) স্বাধীন ভারতের প্রথম ভোটার শ্যাম শরণ নেগি ১০৫ বছর বয়সে মারা গেছেন।
      ভারত স্বাধীন হওয়ার পর ১৯৫১ সালে নির্বাচন শুরু হতেই প্রথম ভোটার হিসেবে
      ভোট দিয়েছিলেন হিমাচলের এই বাসিন্দা। চলতি বছরের ১২ নভেম্বর হিমাচল
      প্রদেশে বিধানসভা নির্বাচন। শ্যাম শরণ নেগি মারা গেলেও পোস্টাল ব্যালটে
      তিনি সেই নির্বাচনে ভোট দিয়ে গেছেন।
 244) অষ্টম টি-২০ বিশ্বকাপ চ্যাম্পিয়ন হয় - ইংল্যান্ড; রানাস আপ দল -
      পাকিস্তান; ম্যান অব দ্য ম্যাচ এবং টুর্নামেন্ট – স্যাম কারেন। - ২০২৪ সালে
      নবম টি-২০ বিশ্বকাপ অনুষ্ঠিত হবে – যুক্তরাষ্ট্র ও ওয়েস্ট ইন্ডিজ।
 245) ঢাকা-আশুলিয়া *এলিভেটেড এক্সপ্রেসওয়ের দৈর্ঘ্য ২৪ কিলোমিটার* এই
      এক্সপ্রেসওয়ের নির্মাণকাজে ব্যয় হবে *১৭ হাজার ৫৫৩ কোটি ৪ লাখ টাকা।*
 246) বাংলাদেশের মহান মুক্তিযুদ্ধে অবদানের জন্য প্রয়াত মার্কিন সিনেটর এডওয়ার্ড
      এম কেনেডি সিনিয়রকে 'ফ্রেন্ডস অব লিবারেশন ওয়ার অনার' প্রদান করেছেন
      প্রধানমন্ত্রী শেখ হাসিনা।
 247) ঢাকা বিশ্ববিদ্যালয়ের ৫৩তম সমাবর্তন অনুষ্ঠানে সম্মানসূচক ডক্টরেট ডিগ্রী
      প্রদান করা হয় *অধ্যাপক ড. জাঁ তিরোল।*
 248) জাতিসংঘ শান্তিরক্ষা মিশনে নারী পুলিশ পাঠানোয় বাংলাদেশ শীর্ষে।
 249) কক্সবাজারের রোহিঙ্গা শিবিরগুলোতে হত্যা-মাদক *'অপারেশন রুট আউট'* নামে
      বিশেষ অভিযান চালানো হয়।
 250) হিমালয়ের প্রায় ৬ হাজার ৩৩২ মিটার উঁচু ডোলমা খাং পর্বত চূড়ায় পা
      রেখেছেন বাংলাদেশি পর্বতারোহী শায়লা বিথী।প্রথম বাংলাদেশি নারী
      হিসেবে তিনি দুর্গম এ পর্বতচূড়ায় পা রাখেন।
 251) বাংলাদেশ সেনাবাহিনীর সার্বিক ব্যবস্থাপনায় আন্তর্জাতিক শান্তিরক্ষা
      অপারেশনের প্রশিক্ষণ সম্পর্কিত আন্তর্জাতিক সংস্থা ইন্টারন্যাশনাল
      অ্যাসোসিয়েশন অব পিসকিপিং ট্রেনিং সেন্টার (আইএপিটিসি) এর ২৬তম বার্ষিক
      সম্মেলন বাংলাদেশ ইনস্টিটিউট অব পিস সাপোর্ট অপারেশন ট্রেনিং (বিপসট),
      রাজেন্দ্রপুর সেনানিবাসে অনুষ্ঠিত হয়।
 252) দেশের প্রথম বাস র‍্যাপিড ট্রানজিট (বিআরটি) নির্মাণের চুক্তি সই করেছে
      সড়ক ও জনপথ অধিদপ্তর ও চীনা গেজৌবা গ্রুপ (China gezhouba group)।
      গাজীপুর থেকে বিমানবন্দর পর্যন্ত বিআরটিএর মূল করিডরের দৈর্ঘ্য হবে সাড়ে
      ২০ কিলোমিটার। যার মধ্যে ১৬ কিলোমিটার হবে সমতলে এবং সাড়ে চার
      কিলোমিটার হবে উড়ালসড়ক।
 253) নোবেল বিজয়ী ফরাসি অর্থনীতিবিদ জ মার্সেল তিহলকে সম্মান সূচক ডিগ্রি
      প্রদানের মধ্য দিয়ে এ পর্যন্ত ৫৩ জনকে সম্মান সূচক ডিগ্রি প্রদান করল ঢাকা
      বিশ্ববিদ্যালয়টি।
 254) বঙ্গবন্ধু, মুক্তিযুদ্ধ ও বাংলাদেশের অভ্যুদয় নিয়ে প্রথম এনসাইক্লোপিডিয়া হলো
      'মুজিবপিডিয়া'। এটি উপমহাদেশের প্রথম পূর্ণাঙ্গ এনসাইক্লোপিডিয়া বা
      জ্ঞানকোষ, যাতে অনুসরণ করা হয়েছে আন্তর্জাতিক মানের গবেষণাপদ্ধতি। ১/৮
      ডিমাই সাইজের দুই খণ্ডের এ বইটিতে রয়েছে ৫৯১টি ভুক্তি ও ৭৫০টি ঐতিহাসিক
      আলোকচিত্র। এর প্রধান সম্পাদক কবি ও গবেষক কামাল চৌধুরী এবং সম্পাদক
      ফরিদ কবির।
 255) নন-ফিকশন বিভাগে কারকাস সাহিত্য পুরস্কার ২০২২ পেয়েছেন বাংলাদেশি
      বংশোদ্ভূত মার্কিন সাহিত্যিক তন্বী নন্দিনী ইসলাম। স্মৃতিকথাধর্মী বই ইন
      সেনসোরিয়াম: নোটস ফর মাই পিপল-এর জন্য ৫০ হাজার মার্কিন ডলার
      অর্থমূল্যের এ পুরস্কার পেলেন তিনি।
 256) "পাবলিক সার্ভিস ও ডিপ্লোমেসি' ক্ষেত্রে 'অনুকরণীয় সাফল্যের জন্য গুসি
      শান্তি পুরস্কার পেয়েছেন শিক্ষামন্ত্রী ডা. দীপু মনি। ওসি শান্তি পুরস্কারটি
      ফিলিপাইনের ম্যানিলায় অবস্থিত গুসি পিস প্রাইজ ফাউন্ডেশনের পক্ষ থেকে
      দেওয়া হয়।
 257) অস্থায়ী মুজিবনগর সরকারকে গার্ড অব অনার দেয়া হামিদুল ইসলাম মারা
      গেছেন। ১৯৭১ সালের ১৭ এপ্রিল অস্থায়ী মুজিবনগর সরকারকে গার্ড অব অনার
      দেয়া ১২ আনসার সদস্যের একজন ছিলেন হামিদুল ইসলাম।
 258) জনগণের সেবা পাওয়া সহজ করার লক্ষ্য নিয়ে বাংলাদেশ পুলিশের বিশেষ শাখা
      উদ্বোধন করে 'হ্যালো এসবি' নামের একটি মোবাইল অ্যাপ। হ্যালো এসবি অ্যাপে
      মাধ্যমে ই-পাসপোর্ট বা এমআরপি পাসপোর্ট নবায়ন বা সংশোধন, ইমিগ্রেশন
      সেবা, দ্বৈত নাগরিকত্ব, ভিসা ইস্যু বা নবায়ন, নিবন্ধন, সিকিউরিটি
      ক্লিয়ারেন্স, এনজিও সংক্রান্ত তথ্য, দত্তক, ভ্রমণ সেবা সহজে পাওয়া যাবে।
      এছাড়া এ সংক্রান্ত কাজে সংশ্লিষ্ট সেবা গ্রহীতারা হ্যালো এসবি অ্যাপের
      মাধ্যমে অভিযোগ ও পরামর্শ দেওয়া বা কোনও তথা দিতে পারবেন।
 259) ১৮ নভেম্বর ২০২২ বাহরাইনের রাজধানী মানামায় বাংলাদেশ এবং উপসাগরীয়
      সহযোগিতা সংস্থা (জিসিসি) এর মধ্যে বিভিন্ন ক্ষেত্রে সহযোগিতার জন্য
      নিয়মিত কনসালটেশনের লক্ষ্যে উভয় পক্ষ একটি সমঝোতা স্মারক স্বাক্ষর করেছে।
 260) রাঙামাটি জেলার জুরাছড়ি উপজেলা সদর সুবলং শাখা বনবিহারে দেশের সর্ববৃহৎ
      সিংহশয্যা বুদ্ধমূর্তি উন্মোচন করা হয়।
 261) ব্রোকারেজ হাউসে চেক জমা দিয়েই শেয়ার কেনার সুযোগ পাবেন শেয়ারবাজারের
      বিনিয়োগকারীরা বিনিয়োগকারীরা এখন থেকে চেক, পে-অর্ডার বা ডিমান্ড
      ড্রাফট জমা দিয়ে দিনে দিনেই শেয়ার কেনার সুযোগ পাবেন।
 262) সবশেষ গতকাল সোমবার *ক্রিশ্চিয়ান এইড ও অ্যাকশনএইড* আফগানিস্তানে কার্যক্রম
      স্থগিত করে। আগের দিন রোববার *কেয়ার ইন্টারন্যাশনাল, দ্য নরওয়েজিয়ান
      রিফিউজি কাউন্সিল (এনআরসি) ও সেভ দ্য চিলড্রেন* একই সিদ্ধান্তের কথা
      জানায়। এ ছাড়া *ইন্টারন্যাশনাল রেসকিউ কমিটিও* আফগানিস্তানে কার্যক্রম
      স্থগিতের কথা জানিয়েছে।
 263) *রোহিঙ্গাদের* বিরুদ্ধে ধর্মীয় বিদ্বেষ ছড়ানোর জন্য আলোচিত–সমালোচিত *বৌদ্ধ ভিক্ষু আশিন উইরাথু*  কে *‘থাইরি পিয়ানছি’*
      পুরস্কার দেওয়ার কথা জানানো হয়

